### ISSUE TITLE
Manually downloaded/extracted cores are not listed in "Load Core"

### ISSUE THREAD

**Issue by davidhedlund** [hizzlekizzle/RetroArch-AppImage#6]
[This is a copy of: https://github.com/libretro/RetroArch/issues/16128]

# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I cannot load any core that I have manually downloaded and extracted to the core directory.

### Expected behavior

Should it not be listed? What have I missed?

### Actual behavior

The `bsnes hd` is not listed in `Load Core`

As [Rob taught me](https://github.com/libretro/RetroArch/issues/16128#issuecomment-1896626987), I had to run:
`./RetroArch-Linux-x86_64.AppImage -L RetroArch-Linux-x86_64.AppImage.home/.config/retroarch/cores/bsnes_hd_beta_libretro.so "~/Downloads/Legend of Zelda, The - A Link to the Past (USA).sfc"`

### Steps to reproduce the bug

* Downloaded http://buildbot.libretro.com/nightly/linux/x86_64/latest/bsnes_hd_beta_libretro.so.zip
* Extracted bsnes_hd_beta_libretro.so.zip
* Moved bsnes_hd_beta_libretro.so to ~/Downloads//RetroArch-Linux-x86_64/RetroArch-Linux-x86_64.AppImage.home/.config/retroarch/cores/
* Opened ~/Downloads//RetroArch-Linux-x86_64/RetroArch-Linux-x86_64.AppImage
* In RetroArch: `Load Core` -- it's empty, the `bsnes-hd beta` core is not listed, so it cannot be loaded.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by davidhedlund** [comment]
Rob [said](https://github.com/libretro/RetroArch/issues/16128#issuecomment-1896626987):

"When you go to Load Core, it doesn't appear? It's likely because the info file isn't there or something. Try passing it as an command line argument.

`retroarch -L mycore.so mycontent.zip`

As for AppImage, make an issue for the repo over at https://github.com/hizzlekizzle/RetroArch-AppImage

AppImage uses its own set of libraries to my knowledge, so there's likely a missing library that bsnes-hd expects if it errors out when loading."

**Comment by RobLoach** [comment]
Do note that after you hit "Load Core", you then need to run "Load Content". Otherwise, you just load the core and don't do anything with it.

The logs for this would help diagnose what's wrong. The other logs you provided didn't really tell us anything.

**Comment by davidhedlund** [comment]
> Do note that after you hit "Load Core", you then need to run "Load Content". Otherwise, you just load the core and don't do anything with it.
> 
> The logs for this would help diagnose what's wrong. The other logs you provided didn't really tell us anything.

The issue is that the core is not even listed in `Load core` as I explained.

**Comment by hizzlekizzle** [comment]
I can't reproduce this issue. I downloaded the appimage and put a core (bsnes-hd_beta) into the portable home's .config/retroarch/cores directory and it popped right up in 'load core'.

**Comment by davidhedlund** [comment]
> I can't reproduce this issue. I downloaded the appimage and put a core (bsnes-hd_beta) into the portable home's .config/retroarch/cores directory and it popped right up in 'load core'.

Thank you very much for helping me.

However, this is not an Appimage issue for me specifically. The issue occurs for me for the Appimage, as well as the for the **retroarch package for GNU/Linux** (just tried it).

**Comment by hizzlekizzle** [comment]
Something is going on somewhere in your system, then, because it should definitely work for a regular linux install (self-compile or whatever). And, of course, "works on my machine"

**Comment by davidhedlund** [comment]
> Something is going on somewhere in your system, then, because it should definitely work for a regular linux install (self-compile or whatever). And, of course, "works on my machine"

Thank you. Since this is not an Appimage issue, I merged the discussion to:
* https://github.com/libretro/RetroArch/issues/16128
